/**
 * Created by fantt on 2017/4/25.
 */
$(function(){
    var count=0;
    var timer;
    showimg();
    function showimg(){
        timer=setInterval(function(){
            count++;
            $(".ul_img_lun").animate({"margin-left":-1375*count+"px"},3000,"linear",function(){
                if(count>=$(".li_img_lun").length-1){
                    $(".ul_img_lun").css("margin-left","0px");
                    count=0;
                }
            });
        },3500);
    }
    $(".li_img_span").each(function(){
        $(this).hover(function(){
            clearInterval(timer);
        },function(){
            showimg();
        }).click(function(){
            if($(this).attr("title")=="l"){
                count++;
                $(".ul_img_lun").animate({"margin-left":-1370*count+"px"},3000,"linear",function(){
                    if(count>=$(".li_img_lun").length-1){
                        $(".ul_img_lun").css("margin-left","0px");
                        count=0;
                    }
                })
            }
            else{
                count--;
                if(count<0){
                    count=$(".li_img_lun").length-2;
                    $(".ul_img_lun").css("margin-left","-2770px");
                }
                $(".ul_img_lun").animate({"margin-left":-1370*count+"px"},3000,"linear");
            }
        });
    });
    $(".li_img_show").each(function(index){
        $(this).mouseenter(function(){
            $(".li_img_show1").eq(index).css("z-index","100");
            $(".li_edu_img_3").eq(index).css("display","block");
        });
    });
    $(".li_img_show1").each(function(index){
        $(this).mouseleave(function(){
            $(".li_img_show1").eq(index).css("z-index","0");
            $(".li_edu_img_3").eq(index).css("display","none");
        });
    });
});